/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defautspackages;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Henock Mkb
 */
public class Ajout extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Ajout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        Nom = new javax.swing.JLabel();
        PostNom = new javax.swing.JLabel();
        Ajout = new javax.swing.JButton();
        ValNom = new javax.swing.JTextField();
        Prenom = new javax.swing.JLabel();
        Facultes = new javax.swing.JLabel();
        Facultes1 = new javax.swing.JLabel();
        Facultes2 = new javax.swing.JLabel();
        Facultes3 = new javax.swing.JLabel();
        ValPrenom = new javax.swing.JTextField();
        ValPostNom = new javax.swing.JTextField();
        ValNumero = new javax.swing.JTextField();
        ValAdresse = new javax.swing.JTextField();
        ValPromotion = new javax.swing.JComboBox<>();
        ValFacultes = new javax.swing.JComboBox<>();
        Annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Container.setBackground(new java.awt.Color(0, 0, 160));

        Nom.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        Nom.setForeground(new java.awt.Color(255, 255, 255));
        Nom.setText("Nom :");

        PostNom.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        PostNom.setForeground(new java.awt.Color(255, 255, 255));
        PostNom.setText("PostNom :");

        Ajout.setText("Ajouter");
        Ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutActionPerformed(evt);
            }
        });

        Prenom.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        Prenom.setForeground(new java.awt.Color(255, 255, 255));
        Prenom.setText("Prenom :");

        Facultes.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        Facultes.setForeground(new java.awt.Color(255, 255, 255));
        Facultes.setText("Faculté :");

        Facultes1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        Facultes1.setForeground(new java.awt.Color(255, 255, 255));
        Facultes1.setText("Promotion :");

        Facultes2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        Facultes2.setForeground(new java.awt.Color(255, 255, 255));
        Facultes2.setText("Adresse :");

        Facultes3.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        Facultes3.setForeground(new java.awt.Color(255, 255, 255));
        Facultes3.setText("Numéro :");

        ValPromotion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AP1", "AP2", "AP3", "IC1", "IC2", "IC3" }));
        ValPromotion.setToolTipText("");

        ValFacultes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analyse et Programmation", "Ingénierie et conception" }));
        ValFacultes.setToolTipText("");

        Annuler.setBackground(new java.awt.Color(255, 51, 51));
        Annuler.setForeground(new java.awt.Color(255, 255, 255));
        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PostNom)
                    .addComponent(Nom)
                    .addComponent(Prenom)
                    .addComponent(Facultes)
                    .addComponent(Facultes1)
                    .addComponent(Facultes2)
                    .addComponent(Facultes3))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ValNom, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValPostNom, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ValPromotion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ValNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(ValAdresse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(ValFacultes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(Annuler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Ajout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nom)
                    .addComponent(ValNom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PostNom)
                    .addComponent(ValPostNom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prenom)
                    .addComponent(ValPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Facultes)
                    .addComponent(ValFacultes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Facultes1)
                    .addComponent(ValPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Facultes2)
                    .addComponent(ValAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Facultes3)
                    .addComponent(ValNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(Ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutActionPerformed
  // Récupération des valeurs saisies dans les champs de texte
    String nom = ValNom.getText();
    String postNom = ValPostNom.getText();
    String prenom = ValPrenom.getText();
    String faculte = ValFacultes.getSelectedItem().toString();
    String promotion = ValPromotion.getSelectedItem().toString();
    String adresse = ValAdresse.getText();
    String numeroText = ValNumero.getText();

// Convertir le numéro en entier (Parsing)

    if (numeroText.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Le champ numéro ne peut pas être vide !");
    return;
} else if (!numeroText.matches("\\d+")) {
    JOptionPane.showMessageDialog(null, "Le champ numéro ne peut contenir que des chiffres !");
    return;
}
    int numero = Integer.parseInt(numeroText);
 

    // Connexion à la base de données
    Connection conn = null;
    try {
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/eifi", "root", "");
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Connexion à la base de donné à echouée !!!");
    }

    // Création de la requête SQL pour insérer les données dans la table "gestap"
    String sql = "INSERT INTO gestap (Nom, PostNom, Prenom, Facultes, Promotion, Adresse, Numero) VALUES (?, ?, ?, ?, ?, ?, ?)";
    try {
        // Préparation de la requête SQL avec les valeurs saisies
        PreparedStatement statement = conn.prepareStatement(sql);
        statement.setString(1, nom);
        statement.setString(2, postNom);
        statement.setString(3, prenom);
        statement.setString(4, faculte);
        statement.setString(5, promotion);
        statement.setString(6, adresse);
        statement.setInt(7, numero);
        // Exécution de la requête SQL
        statement.executeUpdate();
        // Fermeture de la connexion
        conn.close();
        JOptionPane.showMessageDialog(null, "Ajout Réussis !!!");
        
    } catch (SQLException ex) {
        // Gestion des erreurs d'exécution de la requête SQL
        JOptionPane.showMessageDialog(null, "Erreur dans L'ajout!!!");
        ex.printStackTrace();
        return;
    }

   
    // Fermeture de la fenêtre d'ajout
    this.dispose();
    
    Dashboard dashboard = new Dashboard();
    dashboard.setLocationRelativeTo(null);
    dashboard.setVisible(true);
    }//GEN-LAST:event_AjoutActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
       
        this.dispose(); 
            
        Dashboard dashboard = new Dashboard();
        dashboard.setLocationRelativeTo(null);
        dashboard.setVisible(true);   
    
    }//GEN-LAST:event_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 
                Ajout ajout = new Ajout();
            
                ajout.setLocationRelativeTo(null); // Centrer la fenêtre
                ajout.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajout;
    private javax.swing.JButton Annuler;
    private javax.swing.JPanel Container;
    private javax.swing.JLabel Facultes;
    private javax.swing.JLabel Facultes1;
    private javax.swing.JLabel Facultes2;
    private javax.swing.JLabel Facultes3;
    private javax.swing.JLabel Nom;
    private javax.swing.JLabel PostNom;
    private javax.swing.JLabel Prenom;
    private javax.swing.JTextField ValAdresse;
    private javax.swing.JComboBox<String> ValFacultes;
    private javax.swing.JTextField ValNom;
    private javax.swing.JTextField ValNumero;
    private javax.swing.JTextField ValPostNom;
    private javax.swing.JTextField ValPrenom;
    private javax.swing.JComboBox<String> ValPromotion;
    // End of variables declaration//GEN-END:variables
}
